#! /usr/bin/env python
from boto.s3.connection import S3Connection

from aws_keys import AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY

conn = S3Connection(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY)
bucket = conn.get_bucket('staphopia')

rs = bucket.list('ena_queue')

total = 0
for key in rs:
    break

print total
